services:
  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    ports:
      - "8161:8161"  # Web console
      - "61616:61616"  # JMS port
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin